import pytest


@pytest.fixture
def sample_jobs():
    """Minimal set of job records covering key scenarios."""
    return [
        {
            "job_id": "100",
            "job_name": "nf-NFCORE_KREWLYZER_KREWLYZER_FILTER_MAF_(P-0000001-T01-TEST)",
            "user": "user_a",
            "account": "user_a",
            "partition": "cmobic_cpu",
            "state": "COMPLETED",
            "req_cpus": 2,
            "alloc_cpus": 2,
            "submit": "2026-03-30T10:00:00",
            "start": "2026-03-30T10:05:00",
            "end": "2026-03-30T10:05:03",
            "elapsed": "00:00:03",
            "cpu_time_raw": 6,
            "total_cpu": "00:02.223",
            "time_limit": "02:00:00",
            "max_rss_mb": 17.96,
            "req_mem_mb": 12288.0,
            "alloc_mem_mb": 12288.0,
            "node_list": ["node001"],
            "base_job_id": "100",
            "max_gpu_util": None,
            "state_by_jobid": None,
            "req_gpu_type": None,
            "req_gpus": None,
            "alloc_gpu_type": None,
            "alloc_gpus": None,
        },
        {
            "job_id": "101",
            "job_name": "nf-NFCORE_KREWLYZER_KREWLYZER_ANNOTATE_VCF_(P-0000001-T01-TEST)",
            "user": "user_a",
            "account": "user_a",
            "partition": "cmobic_cpu",
            "state": "COMPLETED",
            "req_cpus": 4,
            "alloc_cpus": 4,
            "submit": "2026-03-30T10:10:00",
            "start": "2026-03-30T10:12:00",
            "end": "2026-03-30T10:34:00",
            "elapsed": "00:22:00",
            "cpu_time_raw": 4800,
            "total_cpu": "01:20:00.000",
            "time_limit": "04:00:00",
            "max_rss_mb": 2048.0,
            "req_mem_mb": 8192.0,
            "alloc_mem_mb": 8192.0,
            "node_list": ["node002"],
            "base_job_id": "101",
            "max_gpu_util": None,
            "state_by_jobid": None,
            "req_gpu_type": None,
            "req_gpus": None,
            "alloc_gpu_type": None,
            "alloc_gpus": None,
        },
        {
            "job_id": "102",
            "job_name": "alignment_C-003DS_hg38",
            "user": "user_b",
            "account": "user_b",
            "partition": "cmobic_cpu",
            "state": "COMPLETED",
            "req_cpus": 8,
            "alloc_cpus": 8,
            "submit": "2026-03-30T11:00:00",
            "start": "2026-03-30T11:00:30",
            "end": "2026-03-30T11:45:30",
            "elapsed": "00:45:00",
            "cpu_time_raw": 19200,
            "total_cpu": "05:20:00.000",
            "time_limit": "08:00:00",
            "max_rss_mb": 6000.0,
            "req_mem_mb": 16384.0,
            "alloc_mem_mb": 16384.0,
            "node_list": ["node001"],
            "base_job_id": "102",
            "max_gpu_util": None,
            "state_by_jobid": None,
            "req_gpu_type": None,
            "req_gpus": None,
            "alloc_gpu_type": None,
            "alloc_gpus": None,
        },
        {
            "job_id": "103",
            "job_name": "s_C_00ABC_variant_call",
            "user": "user_b",
            "account": "user_b",
            "partition": "cmobic_cpu",
            "state": "FAILED",
            "req_cpus": 4,
            "alloc_cpus": 4,
            "submit": "2026-03-30T12:00:00",
            "start": "2026-03-30T12:10:00",
            "end": "2026-03-30T12:15:00",
            "elapsed": "00:05:00",
            "cpu_time_raw": 100,
            "total_cpu": "00:01:40.000",
            "time_limit": "02:00:00",
            "max_rss_mb": 500.0,
            "req_mem_mb": 8192.0,
            "alloc_mem_mb": 8192.0,
            "node_list": ["node002"],
            "base_job_id": "103",
            "max_gpu_util": None,
            "state_by_jobid": None,
            "req_gpu_type": None,
            "req_gpus": None,
            "alloc_gpu_type": None,
            "alloc_gpus": None,
        },
        {
            "job_id": "104",
            "job_name": "my_custom_job",
            "user": "user_c",
            "account": "user_c",
            "partition": "cmobic_cpu",
            "state": "TIMEOUT",
            "req_cpus": 2,
            "alloc_cpus": 2,
            "submit": "2026-03-30T14:00:00",
            "start": "2026-03-30T14:30:00",
            "end": "2026-03-30T16:30:00",
            "elapsed": "02:00:00",
            "cpu_time_raw": 7200,
            "total_cpu": "02:00:00.000",
            "time_limit": "02:00:00",
            "max_rss_mb": 4000.0,
            "req_mem_mb": 4096.0,
            "alloc_mem_mb": 4096.0,
            "node_list": ["node003"],
            "base_job_id": "104",
            "max_gpu_util": None,
            "state_by_jobid": None,
            "req_gpu_type": None,
            "req_gpus": None,
            "alloc_gpu_type": None,
            "alloc_gpus": None,
        },
    ]


@pytest.fixture
def sample_jobs_json(tmp_path, sample_jobs):
    """Write sample jobs to a JSON file and return the directory."""
    import json

    filepath = tmp_path / "job_2026-03-30.json"
    filepath.write_text(json.dumps(sample_jobs))
    return tmp_path
